version: '3.8'

services:
  frontend:
    image: dcrkarim/rssreader-frontend:latest
    platform: linux/amd64
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: dcrkarim/rssreader-backend:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_NAME: rssreadersomone
      DB_USER: karimsomone
      DB_PASSWORD: karimsomone
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: rssreadersomone
      POSTGRES_USER: karimsomone
      POSTGRES_PASSWORD: karimsomone
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U karimsomone -d rssreadersomone"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:

volumes:
  pgdata: